#!/bin/bash

#時間別
egrep -o '^"201[0-9]/[01][0-9]/[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]"' target.csv|
tr -d \"            |
awk '$0=$2'         |
sort|uniq -c -w2    |
sed -r "s_^\s+__g"  |
rev                 |
cut -b7-            |
rev                 > zikanbetsu

#月別
egrep -o '^"201[0-9]/[01][0-9]/[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]"' target.csv|
tr -d \"            |
uniq -w7 -c         |
sed -r 's_^\s+__g'  |
rev                 |
cut -b13-           |
rev                 > tsukibetsu
